[package]
name = "athena-welcome-rs"
version = "0.1.0"
edition = "2021"


[dependencies]
anyhow = "1.0.79"
dirs = "5.0.1"
gtk = { version = "0.7.3", package = "gtk4", features = ["v4_12"] }
lazy_static = "1.4.0"
serde = {version = "1.0", features = ["derive"] }
toml = "0.8.8"
whoami = "1.4.1"
strum = "0.25"
strum_macros = "0.25"
